name 'trial_cook'
maintainer 'Jared Weyer'
maintainer_email 'jweyermtb8@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures trial_cook'
version '0.1.0'
chef_version '>= 16.0'

depends 'macos'
depends 'homebrew'
